### ISSUE TITLE
Why not put in the readme what this component is for in the first place? 

### ISSUE THREAD

**Issue by dzonekl** [bebraw/react-ghfork#5]

**Comment by bebraw** [comment]
PR welcome. :)

**Comment by bebraw** [comment]
Btw, https://www.npmjs.com/package/react-github-fork-ribbon seems like a more modern version of the same.

**Comment by dzonekl** [comment]
haha, yeah right.

**Comment by bebraw** [comment]
I added a brief description. Feel free to improve.
